name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    tags: ['v*']
  pull_request:
    branches: [main]

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  package-bin:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install build deps
        run: |
          sudo apt update
          sudo apt install -y cmake libgl1-mesa-dev libglu1-mesa-dev qt6-base-dev libqt6widgets6
      - name: Build
        working-directory: src/cpp
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Rename binary
        run: mv src/cpp/build/sticky src/cpp/build/sticky-1.0.0.bin
      - name: Upload .bin
        uses: actions/upload-artifact@v5
        with:
          name: pkg-bin
          path: src/cpp/build/sticky-1.0.0.bin
          retention-days: 7

  # Здесь будет package-arch, просто я заебался.

  package-deb:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install build deps
        run: |
          sudo apt update
          sudo apt install -y cmake libgl1-mesa-dev libglu1-mesa-dev qt6-base-dev libqt6widgets6
      - name: Build DEB
        working-directory: src/cpp
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCPACK_PACKAGE_SUFFIX=-qt6
          cmake --build build
          cd build && cpack -G DEB

      - uses: actions/upload-artifact@v5
        with:
          name: pkg-deb
          path: "src/cpp/build/*.deb"
          retention-days: 7

  package-rpm:
    runs-on: ubuntu-24.04
    container:
      image: fedora:latest
    steps:
      - uses: actions/checkout@v5
      - name: Install build deps
        run: |
          dnf install -y cmake gcc-c++ make rpm-build mesa-libGL-devel mesa-libGLU-devel qt6-qtbase-devel
      - name: Build RPM
        working-directory: src/cpp
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCPACK_PACKAGE_SUFFIX=-qt6
          cmake --build build
          cd build && cpack -G RPM

      - uses: actions/upload-artifact@v5
        with:
          name: pkg-rpm
          path: "src/cpp/build/*.rpm"
          retention-days: 7

  publish-release:
    name: Create GitHub Release
    needs: [package-deb, package-rpm, package-bin]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create release directory
        run: mkdir -p release-files

      - name: Download .deb
        uses: actions/download-artifact@v5
        with:
          name: pkg-deb
          path: release-files

      - name: Download .rpm
        uses: actions/download-artifact@v5
        with:
          name: pkg-rpm
          path: release-files

      - name: Download .bin
        uses: actions/download-artifact@v5
        with:
          name: pkg-bin
          path: release-files

      - name: Upload Files to Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-files/**/*
          generate_release_notes: true
          draft: false
          prerelease: false
